[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/upload-drive"
  to   = "/.netlify/functions/upload-drive"
  status = 200

[[redirects]]
  from = "/gallery"
  to   = "/.netlify/functions/gallery"
  status = 200

[[redirects]]
  from = "/image/*"
  to   = "/.netlify/functions/image/:splat"
  status = 200

[[redirects]]
  from = "/auth"
  to   = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/oauth2callback"
  to   = "/.netlify/functions/oauth2callback"
  status = 200

# keep this LAST if you use a SPA front-end
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200
